/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyAdsRouteImport } from './routes/_authenticated/my-ads'
import { Route as AuthenticatedFavouritesRouteImport } from './routes/_authenticated/favourites'
import { Route as AuthenticatedEditProfileRouteImport } from './routes/_authenticated/edit-profile'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats.index'
import { Route as AuthenticatedChatsIdRouteImport } from './routes/_authenticated/chats.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyAdsRoute = AuthenticatedMyAdsRouteImport.update({
  id: '/my-ads',
  path: '/my-ads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavouritesRoute = AuthenticatedFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditProfileRoute =
  AuthenticatedEditProfileRouteImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatsIdRoute = AuthenticatedChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/my-ads': typeof AuthenticatedMyAdsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/my-ads': typeof AuthenticatedMyAdsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/_authenticated/edit-profile': typeof AuthenticatedEditProfileRoute
  '/_authenticated/favourites': typeof AuthenticatedFavouritesRoute
  '/_authenticated/my-ads': typeof AuthenticatedMyAdsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/_authenticated/chats/$id': typeof AuthenticatedChatsIdRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/search'
    | '/edit-profile'
    | '/favourites'
    | '/my-ads'
    | '/notifications'
    | '/profile'
    | '/sell'
    | '/settings'
    | '/category/$slug'
    | '/product/$id'
    | '/chats/$id'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/search'
    | '/edit-profile'
    | '/favourites'
    | '/my-ads'
    | '/notifications'
    | '/profile'
    | '/sell'
    | '/settings'
    | '/category/$slug'
    | '/product/$id'
    | '/chats/$id'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/search'
    | '/_authenticated/edit-profile'
    | '/_authenticated/favourites'
    | '/_authenticated/my-ads'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/sell'
    | '/_authenticated/settings'
    | '/category/$slug'
    | '/product/$id'
    | '/_authenticated/chats/$id'
    | '/_authenticated/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-ads': {
      id: '/_authenticated/my-ads'
      path: '/my-ads'
      fullPath: '/my-ads'
      preLoaderRoute: typeof AuthenticatedMyAdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favourites': {
      id: '/_authenticated/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AuthenticatedFavouritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edit-profile': {
      id: '/_authenticated/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthenticatedEditProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chats/$id': {
      id: '/_authenticated/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthenticatedChatsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEditProfileRoute: typeof AuthenticatedEditProfileRoute
  AuthenticatedFavouritesRoute: typeof AuthenticatedFavouritesRoute
  AuthenticatedMyAdsRoute: typeof AuthenticatedMyAdsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChatsIdRoute: typeof AuthenticatedChatsIdRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEditProfileRoute: AuthenticatedEditProfileRoute,
  AuthenticatedFavouritesRoute: AuthenticatedFavouritesRoute,
  AuthenticatedMyAdsRoute: AuthenticatedMyAdsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChatsIdRoute: AuthenticatedChatsIdRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
